### ISSUE TITLE
merge ro.product from official OnePlus Nord to LineageOS 17.1.x OP Nord Build

### ISSUE THREAD

**Issue by thigazi** [CryllicBuster273/android_vendor_oneplus_avicii#1]
Hello Akshay,

As i know you are maintaining the LineageOS for OnePlus nord.
In the past I always had problems with certain apps, especially Samsung Wear as the Application couldn't identify through the os properties the phone.

Especially for the LineageOS build, can we merge most of the offical os "ro.product.*" build strings into the lineageos version for the OnePlus Nord series ?

For example we can take ro.product.board, ro.product.brand, ro.product.cpu.*,ro.product.cuptsm,ro.product.device,ro.product.first_api_level,ro.product.manufactur,ro.product.model,ro.product.name,ro.product.odm.*ro.product.product.*,ro.product.system.*,ro.product.vendor.*

What do you think of it ? 
In case of that, Samsung Wearable, Banking Apps would run then without any problems despite of LineageOS....

best, Tamer

Here is the getproperties from the current OxygenOS 10.5.11.AC01BA, OP Nord European Version AC2003:

[ro.product.board]: [lito]
[ro.product.brand]: [OnePlus]
[ro.product.build.date]: [Thu Feb  4 02:42:50 CST 2021]
[ro.product.build.date.utc]: [1612377770]
[ro.product.build.fingerprint]: [OnePlus/Nord_EEA/Nord:10/QKQ1.200412.002/2102040230:user/release-keys]
[ro.product.build.id]: [QKQ1.200412.002]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [2102040230]
[ro.product.build.version.release]: [10]
[ro.product.build.version.sdk]: [29]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.cuptsm]: [ONEPLUS|ESE|01|02|80T]
[ro.product.device]: [Nord]
[ro.product.first_api_level]: [29]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [OnePlus]
[ro.product.model]: [AC2003]
[ro.product.name]: [Nord_EEA]
[ro.product.odm.brand]: [OnePlus]
[ro.product.odm.device]: [Nord]
[ro.product.odm.manufacturer]: [OnePlus]
[ro.product.odm.model]: [AC2003]
[ro.product.odm.name]: [Nord_EEA]
[ro.product.product.brand]: [OnePlus]
[ro.product.product.device]: [Nord]
[ro.product.product.manufacturer]: [OnePlus]
[ro.product.product.model]: [AC2003]
[ro.product.product.name]: [Nord_EEA]
[ro.product.system.brand]: [OnePlus]
[ro.product.system.device]: [Nord]
[ro.product.system.manufacturer]: [OnePlus]
[ro.product.system.model]: [AC2003]
[ro.product.system.name]: [Nord_EEA]
[ro.product.vendor.brand]: [OnePlus]
[ro.product.vendor.device]: [Nord]
[ro.product.vendor.manufacturer]: [OnePlus]
[ro.product.vendor.model]: [AC2003]
[ro.product.vendor.name]: [Nord_EEA]

**Comment by KakatkarAkshay** [comment]
We are not allowed to modify build fingerprint and build identification props on official builds

**Comment by thigazi** [comment]
I ment everything else EXCEPT the "ro.product.build.*", values.
Only the others.

Only those:

**[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.cuptsm]: [ONEPLUS|ESE|01|02|80T]
[ro.product.device]: [Nord]
[ro.product.first_api_level]: [29]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [OnePlus]
[ro.product.model]: [AC2003]
[ro.product.name]: [Nord_EEA]
[ro.product.odm.brand]: [OnePlus]
[ro.product.odm.device]: [Nord]
[ro.product.odm.manufacturer]: [OnePlus]
[ro.product.odm.model]: [AC2003]
[ro.product.odm.name]: [Nord_EEA]
[ro.product.product.brand]: [OnePlus]
[ro.product.product.device]: [Nord]
[ro.product.product.manufacturer]: [OnePlus]
[ro.product.product.model]: [AC2003]
[ro.product.product.name]: [Nord_EEA]
[ro.product.system.brand]: [OnePlus]
[ro.product.system.device]: [Nord]
[ro.product.system.manufacturer]: [OnePlus]
[ro.product.system.model]: [AC2003]
[ro.product.system.name]: [Nord_EEA]
[ro.product.vendor.brand]: [OnePlus]
[ro.product.vendor.device]: [Nord]
[ro.product.vendor.manufacturer]: [OnePlus]
[ro.product.vendor.model]: [AC2003]
[ro.product.vendor.name]: [Nord_EEA]**


best, Tamer
